Add lib/udge/check

diff --git a/lib/udge/check b/lib/udge/check
--- a/lib/udge/check
+++ b/lib/udge/check
@@ -25,6 +25,12 @@
 #   check path/to/problem path/to/out
 prefix="$(dirname "$(dirname "$(dirname "$0")")")"
 . "$prefix/lib/udge/core"
+
+fail() {
+	echo "$@"
+	exit 1
+}
+
 set="$1"
 out="$2"
 verbose="$3"
@@ -35,6 +41,45 @@ verbose="$3"
 [ -d "$set" ] || errxit "input folder not found"
 [ -d "$out" ] || errxit "output folder not found"
 
+check-exit-code() {
+	[ "$1" = 0 ]
+}
+
+check-out() {
+	if [ -n "$verbose" ]
+	then
+		diff -rud "$1" "$2"
+	else
+		diff -q "$1" "$2" >/dev/null
+	fi
+}
+
+check-1() {
+	sol=$1
+	run=$2
+
+	# checks that it is compiled
+	[ -e $run/exe* ] || fail "No - compile error"
+
+	# sandboxing checks
+	grep -q "udge-sandbox: fork: .* unavailable" $run/err && fail "No - reached maximum number of processes"
+	grep -q "^timeout: sending signal TERM"      $run/err && fail "No - time limit exceeded"
+
+	# checks the exit code
+	checkexitcode=check-exit-code
+	[ -x $sol/check-exit-code ] && checkexitcode=$sol/check-exit-code
+	$checkexitcode $(cat $run/exit) || fail "No - runtime error (non-zero exit code)"
+
+	# checks standard output and standard error
+	check=check-out
+	[ -x $sol/check-out ] && check=$sol/check-out
+	$check $sol/sol $run/out || fail "No - wrong output"
+	if [ -e $sol/err ]
+	then
+		$check $sol/err $run/err || fail "No - wrong error output"
+	fi
+}
+
 total=0
 outof=`n-points "$problem"`
 for idir in $set/*/
@@ -44,6 +89,6 @@ do
 	odir=$out$id
 	pts=`cator1 $idir/pts`
 	[ -n "$verbose" ] && echo "Conferring $odir against $idir"
-	true && ((total+=$pts)) || break
+	check-1 $idir $odir && ((total+=$pts)) || break
 done
 echo $total/$outof
