Support testing stderr output

diff --git a/lib/udge/compile-and-test b/lib/udge/compile-and-test
--- a/lib/udge/compile-and-test
+++ b/lib/udge/compile-and-test
@@ -100,3 +100,7 @@ check-out() {
 check=check-out
 [ -x ./check-out ] && check=./check-out
 $check sol stdout || fail "No - wrong output"
+if [ -e err ]
+then
+	$check err stderr || fail "No - wrong error output"
+fi
