use just >&2 instead of 1>&2

diff --git a/bin/udge-latest-results b/bin/udge-latest-results
--- a/bin/udge-latest-results
+++ b/bin/udge-latest-results
@@ -4,9 +4,9 @@
 prefix="$(dirname "$(dirname "$0")")"
 . "$prefix/lib/udge/core"
 errxit() {
-	echo "$0, error: $@" 1>&2
-	echo "usage:"        1>&2
-	echo "  $0 <user>"   1>&2
+	echo "$0, error: $@" >&2
+	echo "usage:"        >&2
+	echo "  $0 <user>"   >&2
 	exit 1
 }
 user="$1"
diff --git a/lib/udge/core b/lib/udge/core
--- a/lib/udge/core
+++ b/lib/udge/core
@@ -13,13 +13,13 @@ SANE='^[a-z_][a-z0-9_-]*$'
 SANE_EMAIL='^[a-z0-9][a-z0-9._%+-]*@[a-z0-9.-]+\.[a-z0-9.-]+$'
 
 errxit() {
-	# We use 1>&2 here instead of /dev/stderr.
+	# We use >&2 here instead of /dev/stderr.
 	#
 	# For some reason I was getting the following error when running scripts
 	# from cron:
 	#
 	#     CROND: (user) CMDOUT (/usr/local/lib/udge/core: line 18: /dev/stderr: Permission denied)
-	echo "`basename "$0"`, error: $@" 1>&2
+	echo "`basename "$0"`, error: $@" >&2
 	exit 1
 }
 
