cgi-bin/udge-new-user: short-circuit user check
move user checks into a function
and short circuit as soon as a problem is found

diff --git a/cgi-bin/udge-new-user b/cgi-bin/udge-new-user
--- a/cgi-bin/udge-new-user
+++ b/cgi-bin/udge-new-user
@@ -91,6 +91,30 @@ has-error() {
 }
 
 
+check-user() {
+	[ -s "$user_fn" ] || {
+		echo "username is missing"
+		return
+	}
+	sane-file "$user_fn" || {
+		echo "invalid characters: use lowercase English letters, digits, dashes (-) or underscores (_)"
+		return
+	}
+	valid-user "$user_fn" || {
+		echo "username already exists, pick another"
+		return
+	}
+	[ "`wc -c <$user_fn`" -le 18 ] || {
+		echo "username must have at most 18 characters"
+		return
+	}
+	[ "`wc -c <$user_fn`" -ge  4 ] || {
+		echo "username must have at least 4 characters"
+		return
+	}
+}
+
+
 check-password() {
 	[ -s "$password_fn" ] || {
 		echo "password is missing"
@@ -125,11 +149,7 @@ post() {
 	email_confirmation_value="`html-cat "$email_confirmation_fn"`"
 
 	diff -q $email_fn $email_confirmation_fn >/dev/null 2>/dev/null || email_error="emails do not match"
-	[ "`wc -c <$user_fn`" -ge  4 ] || user_error="username must have at least 4 characters"
-	[ "`wc -c <$user_fn`" -le 18 ] || user_error="username must have at most 18 characters"
-	valid-user "$user_fn"          || user_error="username already exists, pick another"
-	sane-file "$user_fn"           || user_error="invalid characters: use lowercase English letters, digits, dashes (-) or underscores (_)"
-	[ -s "$user_fn" ]              || user_error="username is missing"
+	user_error="`check-user`"
 	password_error="`check-password`"
 	sane-email-file "$email_fn" || email_error="invalid or unsupported email address"
 	[ -s "$email_fn" ]          || email_error="email is missing"
